//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietGearStore._1511060754.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class datalinhkienEntities : DbContext
    {
        public datalinhkienEntities()
            : base("name=datalinhkienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Lienhe> Lienhes { get; set; }
        public virtual DbSet<Lienlac> Lienlacs { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Logo> Logoes { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Info> Infoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<News> News { get; set; }
    }
}
